assembly:
  accession: GCA_002217835.1
  alias: Dobs_1.0
  bioproject: PRJDB4578
  biosample: SAMD00047210
  level: scaffold
  prefix: BDQP01
  scaffold-count: 1935
  span: 181868570
reads:
  paired:
  - [DRR055278, ILLUMINA]
  - [DRR055279, ILLUMINA]
  - [DRR055280, ILLUMINA]
settings:
  chunk: 1000000
  taxonomy: /software/databases/ncbi_2018_05/taxonomy
  tmp: /tmp
similarity:
  databases:
  - idmap: [nucl_est, nucl_gb, nucl_gss, nucl_wgs, pdb]
    local: /software/databases/ncbi_2018_05
    name: nt
    source: ncbi
    tool: blast
    type: nucl
  - local: /software/databases/uniprot_2018_04
    max_target_seqs: 1
    name: reference_proteomes
    source: uniprot
    tool: diamond
    type: prot
  defaults:
    evalue: 1e-25
    mask_ids: [7215]
    max_target_seqs: 10
    root: 1
  taxrule: bestsumorder
taxon:
  name: Drosophila obscura
  taxid: 7282
  family: Drosophilidae
  phylum: Arthropoda
