similarity:
  taxrule: bestsumorder
  defaults:
    type: nucl
    tool: blast
    source: ncbi
    local: /path/to/ncbi_2018_03
    root: 1
    evalue: 1e-25
    max_target_seqs: 10
  databases:
    - type: nucl
      name: nt
      idmap:
        - nucl_est
        - nucl_gb
        - nucl_gss
        - nucl_wgs
        - pdb
    - name: reference_proteomes
      type: prot
      tool: diamond
      source: uniprot
      local: /path/to/uniprot_2018_02
      max_target_seqs: 1
settings:
  taxonomy: /path/to/ncbi_taxonomy
  tmp: /tmp
  chunk: 1000000
