similarity:
  taxrule: bestsumorder
  defaults:
    root: 1
    evalue: 1e-25
    max_target_seqs: 10
  databases:
    - type: nucl
      name: nt
      type: nucl
      tool: blast
      source: ncbi
      local: /software/databases/ncbi_2018_08
      idmap:
        - nucl_est
        - nucl_gb
        - nucl_gss
        - nucl_wgs
        - pdb
    - name: reference_proteomes
      type: prot
      tool: diamond
      source: uniprot
      local: /ceph/software/databases/uniprot_2018_07
      max_target_seqs: 1
settings:
  chunk: 1000000
  blast_chunk: 100000
  blast_overlap: 500
  blast_max_chunks: 10
  taxonomy: /software/databases/ncbi_2018_08/taxonomy
  tmp: /tmp
  blobtools_path: /software/blobtools
  blast_path: /software/blast/ncbi-blast-2.8.0+/bin
reads:
  coverage:
    min: 2
    max: 100
