similarity:
  taxrule: bestsumorder
  defaults:
    root: 1
    evalue: 1e-25
    max_target_seqs: 10
  databases:
    - type: nucl
      name: nt
      type: nucl
      tool: blast
      source: ncbi
      local: /ceph/software/databases/ncbi_2018_04
      idmap:
        - nucl_est
        - nucl_gb
        - nucl_gss
        - nucl_wgs
        - pdb
    - name: reference_proteomes
      type: prot
      tool: diamond
      source: uniprot
      local: /ceph/software/databases/uniprot_2018_03
      max_target_seqs: 1
settings:
  taxonomy: /ceph/software/databases/ncbi_taxonomy
  tmp: /dev/shm
  chunk: 1000000
